version: '3.8'
services:
  smtp:
    image: namshi/smtp
    ports:
      - '25:25'
    environment:
        - SMTP_USER=admin
        - SMTP_PASS=admin
  db:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=designermatch
    ports:
      - '5435:5432'
    expose:
      - '5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local